# Generated by Django 5.2.13 on 2026-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
